package microdesc

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"os"
	"strings"
	"testing"
)

// tor-test-md.fixture is test_md2_25 from Tor's official test_microdesc.c,
// maint-0.4.7 (Tor Project, BSD-3-Clause). It was generated by chutney.
// https://raw.githubusercontent.com/torproject/tor/maint-0.4.7/src/test/test_microdesc.c
func TestOfficialMicrodescriptor(t *testing.T) {
	data, err := os.ReadFile("tor-test-md.fixture")
	if err != nil {
		t.Fatal(err)
	}
	digest := sha256.Sum256(data)
	d := base64.RawStdEncoding.EncodeToString(digest[:])
	out, err := (Parser{}).Parse(bytes.NewReader(data), []string{d, d})
	if err != nil {
		t.Fatal(err)
	}
	if len(out) != 2 || out[0] == nil || out[1] == nil || len(out[0].NTorOnionKey) != 32 || !out[0].ExitRules.IsAllowed(443) {
		t.Fatal("official descriptor not hydrated")
	}
	for name, input := range map[string][]byte{"truncated": data[:len(data)-1], "added-newline": append(bytes.Clone(data), '\n'), "crlf": bytes.ReplaceAll(data, []byte("\n"), []byte("\r\n")), "corrupt": bytes.Replace(data, []byte("accept"), []byte("reject"), 1)} {
		t.Run(name, func(t *testing.T) {
			got, err := (Parser{}).Parse(bytes.NewReader(input), []string{d})
			if err == nil && got[0] != nil {
				t.Fatal("accepted altered digest bytes")
			}
		})
	}
	for _, suffix := range []string{"family $\n", "family-ids missing-colon\n", "id ed25519 AA\n", "p accept 1-999999999\n", strings.Repeat("x", 65536) + "\n"} {
		input := append(bytes.Clone(data), []byte(suffix)...)
		dig := sha256.Sum256(input)
		if _, err := (Parser{}).Parse(bytes.NewReader(input), []string{base64.RawStdEncoding.EncodeToString(dig[:])}); err == nil {
			t.Fatal("accepted malformed descriptor")
		}
	}
}
